In [16]:
import pandas as pd

In [28]:
data = pd.read_csv("data/attacks.csv",encoding = "ISO-8859-1")

In [29]:
# Esta funciones me van a ayudar a quitarle a los valores de fecha todo lo que sobra que no sea dd/mm/aaaa y también
# le dará formato en caso de que lo necesite

def year_sure(palabra):
    # quiero garantizar que todas mis entradas terminen con el año además, esta función me garantiza que
    #limpiar fecha no borre por error ningún dato. A lo mejor debería juntarlas ambas
    palabra = str(palabra)
    palabra = palabra.strip()
    respuesta = str(palabra)
    
    while len(respuesta) > 0:
        
        if respuesta[-1].isnumeric():
            return respuesta
        else:
            #print (respuesta)
            respuesta = respuesta[:-1]
            
    #return palabra



def limpiar_fecha (palabra):
    # primero creo todo lo que voy a necesitar
    palabra = str(palabra)
    fecha_limpia = str()
    
    palabra = palabra.strip()
    for letra in reversed(palabra):
        if letra != ' ':
            fecha_limpia += letra
        else:
            return fecha_limpia[::-1]
    
    return palabra

        
def meses_to_num(palabra):
    
    palabra = str(palabra)
    meses_dict = {'Jan' : '01', 'Feb' : '02', 'Mar' : '03', 'Apr' : '04', 'May' : '05', 'Jun' : '06', 'Jul' : '07',
              'Aug' : '08', 'Sep' : '09', 'Oct' : '10', 'Nov' : '11', 'Dec' : '12',}
    
    palabra = palabra.strip()
    for key, value in meses_dict.items():
        if key in palabra:
            palabra = palabra.replace(key, value)
    
    palabra = palabra.replace('-', '/')
    return palabra

In [ ]:
data

In [30]:
data['Date'] = data['Date'].apply(year_sure)

In [31]:
data['Date'] = data['Date'].apply(limpiar_fecha)

In [32]:
data['Date'] = data['Date'].apply(meses_to_num)

In [33]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25/06/2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18/06/2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09/06/2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08/06/2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04/06/2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN